.TH fstrm_replay 1

.SH NAME

fstrm_replay \- Replay saved Frame Streams data to a socket connection.

.SH SYNOPSIS

.B fstrm_replay -t \fIcontent-type\fB -r \fIfile\fB [ -r \fIfile\fB ... ]
.br
.B "	[ -u \fIsocket-path\fB ] [ -a \fIIP\fB -p \fIport\fB ]"

.SH DESCRIPTION

.B fstrm_replay
connects to a Frame Streams receive on either the given UNIX domain
\fIsocket-path\fR or TCP \fIaddress\fR and \fIport\fR, then reads
and sends data of the supplied \fIcontent-type\fR from the given
\fIfiles\fR.

.SH OPTIONS

.TP
.B -t \fIcontent-type\fB
Specify the \fIcontent-type\fR to read from files and send to the
Frame Streams socket. Files whose content-type differs are skipped.
If the socket server does not accept the \fIcontent-type\fR,
fIfstrm_replay\fR will fail.

.TP
.B -r \fIfile\fB
Read data from \fIfile\fR. Multiple files can be given with multiple
\fB-r\fR options. Files which cannot be opened, or do not contain valid
Frame Streams data will be skipped.

.TP
.B -u \fIsocket-path\fB
Connect to \fIsocket-path\fR to write Frame Streams data. Only one of
\fB-u\fR or \fB-a\fR may be given.

.TP
.B -a \fIIP\fB
Connect to address \fIIP\fR to write Frame Streams data. Only one of
\fB-u\fR or \fB-a\fR may be given. Use of \fB-a\fR requires a port
given with \fB-p\fR.

.TP
.B -p \fIport\fB
If \fB-a\fR is given, use TCP port \fIport\fR to write Frame Streams
data.

.SH EXAMPLES

Replay dnstap data over UNIX domain socket:

.nf
	fstrm_replay -t protobuf:dnstap.Dnstap \\
		-u /var/run/named/dnstap.sock -r dnstap-log.fstrm
.fi
